### ISSUE TITLE
Router only implemented in linux

### ISSUE THREAD

**Issue by Buba5473** [liamg/furious#6]
I compiled furious for Windows using "go get github.com/liamg/furious"

There are two problems: on "furious -s device host" it gives a DOWN response, but it also shows the MAC address and open ports.
The second problem: when executing "furious host" produces

C:\Users\i.eremeev\go\bin>furious 192.168.2.35

Starting scan at 2019-09-17 09:33:42.3653148 +0700 +07 m=+0.017996401

panic: router only implemented in linux

goroutine 23 [running]:
github.com/google/gopacket/routing.New(...)
        C:/Users/i.eremeev/go/pkg/mod/github.com/google/gopacket@v1.1.17/routing/other.go:14
github.com/liamg/furious/scan.(*SynScanner).scanHost(0xc0002aa000, 0xc000280110, 0x10, 0x10, 0xc00025a000, 0x16b4, 0x1c00, 0xc00027c240, 0xc000b0e000, 0x7c6b80, ...)
        C:/Users/i.eremeev/go/pkg/mod/github.com/liamg/furious@v0.0.0-20190619180719-b76d3ae59fcc/scan/scan-syn.go:242 +0x269
github.com/liamg/furious/scan.(*SynScanner).Start.func1(0xc0002aa000)
        C:/Users/i.eremeev/go/pkg/mod/github.com/liamg/furious@v0.0.0-20190619180719-b76d3ae59fcc/scan/scan-syn.go:74 +0x17a
created by github.com/liamg/furious/scan.(*SynScanner).Start
        C:/Users/i.eremeev/go/pkg/mod/github.com/liamg/furious@v0.0.0-20190619180719-b76d3ae59fcc/scan/scan-syn.go:68 +0x4a

**Comment by sxueck** [comment]
https://github.com/liamg/furious/issues/5

**Comment by Buba5473** [comment]
Closed
